[package]
name = "runir"
version = "0.1.0"
edition = "2024"

[features]
default = ["tokio"]
tokio = ["dep:tokio", "dep:async-compat"]
cli = ["dep:serde_json", "dep:serde_yaml", "dep:clap"]

[dependencies]
ahash = "0.8.12"
ascii = "1.1.0"
async-stream = "0.3.6"
bitflags = "2.9.1"
bytes = "1.10.1"
crc = "3.3.0"
flexbuffers = "25.2.10"
futures = "0.3.31"
hex = "0.4.3"
scalable_cuckoo_filter = { version = "0.4.0", features = ["serde_support"] }
crossbeam = { version = "0.8.4", features = ["crossbeam-queue"] }
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.9"
time = "0.3.41"
toml = "0.8.23"
tracing = "0.1.41"
tracing-test = "0.2.5"
unicode-segmentation = "1.12.0"
uuid = "1.17.0"
dashmap = "6.1.0"
asynchronous-codec = "0.7.0"
parking_lot = "0.12.4"
stackfuture = "0.3.0"
tracing-subscriber = "0.3.19"
pin-project-lite = "0.2.16"

# TODO: This would only be available in a full-fledged OS runtime
memmap2 = "0.9.5"
tokio = { version = "1.45.1", features = ["full"], optional = true }
async-compat = { version = "0.2.4", optional = true }
clap =  { version = "4.5.40", features = ["derive", "env"], optional = true }
serde_json = { version = "1.0.140", optional = true }
serde_yaml = { version = "0.9.34", optional = true }
anyhow = "1.0.98"
zstd = "0.13.3"
generic-array = "1.2.0"
either = "1.15.0"

[[bin]]
name = "runir"
required-features = ["cli"]
